// constants.js

const SET_LOGININFO = 'SET_LOGININFO';
const SET_ACTIVECOMPANY = 'SET_ACTIVECOMPANY';
const SET_ROUTEHISTORY = 'SET_ROUTEHISTORY';
const SET_ACTIVEBRANCH = 'SET_ACTIVEBRANCH';
const SET_DATAACTIONTRIGGER = 'SET_SAVETRIGGER';

export {
    SET_LOGININFO,
    SET_ACTIVECOMPANY,
    SET_ROUTEHISTORY,
    SET_ACTIVEBRANCH,
    SET_DATAACTIONTRIGGER
};

