// constants.js

//SESSION
const SET_LOGININFO = 'SET_LOGININFO';

//ACTIVE COMPANY
const SET_ACTIVECOMPANY = 'SET_ACTIVECOMPANY';

//ROUTE INFORMATION
const SET_ROUTEHISTORY = 'SET_ROUTEHISTORY';

//ACTIVE BRANCH
const SET_ACTIVEBRANCH = 'SET_ACTIVEBRANCH';

//DATA ACTION TRIGGER
const SET_DATAACTIONTRIGGER = 'SET_DATAACTIONTRIGGER';

//ACTIVECOMPANY
const SET_ACTIVECOMPANYID = 'SET_ACTIVECOMPANYID';

//Company Policies
const GET_WORKSHIFT = 'GET_WORKSHIFT';

//DB Fetching functions
const FETCH_HAS_ERRORED = 'FETCH_HAS_ERRORED';
const FETCH_IS_LOADING = 'FETCH_IS_LOADING';

export {
    SET_LOGININFO,
    SET_ACTIVECOMPANY,
    SET_ROUTEHISTORY,
    SET_ACTIVEBRANCH,
    SET_DATAACTIONTRIGGER,
    SET_ACTIVECOMPANYID,
    GET_WORKSHIFT,
    FETCH_HAS_ERRORED,
    FETCH_IS_LOADING
};

